// Loads Excalidraw's own library-import and restore code under jsdom, so tests can run the
// built Library through the same path Excalidraw uses when a library is opened or an item placed.
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);

type El = Record<string, any>;
export type Excalidraw = {
  loadLibraryFromBlob(blob: Blob, status: string): Promise<{ id: string; name?: string; elements: El[] }[]>;
  restoreElements(elements: El[], local: null, opts?: Record<string, boolean>): El[];
  getCommonBounds(elements: El[]): [number, number, number, number];
};

export async function loadExcalidraw(which: "fork" | "upstream"): Promise<Excalidraw> {
  require("./setup.cjs");
  if (which === "fork") {
    // The bundle the Obsidian Excalidraw plugin embeds.
    // Not in the package's exports, so load it by path.
    require(fileURLToPath(new URL("../node_modules/@zsviczian/excalidraw/dist/obsidian/excalidraw.production.min.js", import.meta.url)));
    return (globalThis as any).ExcalidrawLib;
  }
  // @ts-ignore: generated by test/bundle-upstream.ts (npm pretest)
  return await import("../.cache/excalidraw-upstream.mjs");
}

// Excalidraw reads library files with jsdom's FileReader, which only accepts jsdom's Blob.
export const libraryBlob = (json: unknown): Blob =>
  new (globalThis as any).window.Blob([JSON.stringify(json)], { type: "application/vnd.excalidrawlib+json" });
