// Every Symbol, in Library order: by family, each ANSI Variant directly after its IEC Symbol.
import type { SymbolDefinition } from "./build.ts";
import {
  capacitor,
  coredInductor,
  crystal,
  ferriteBead,
  fuse,
  fuseAnsi,
  inductor,
  polarizedCapacitor,
  potentiometer,
  potentiometerAnsi,
  resistor,
  resistorAnsi,
  transformer,
  variableCapacitor,
} from "./symbols/passives.ts";
import { led, photodiode, plainDiode, schottky, varactor, zener } from "./symbols/diodes.ts";
import { comparator, nJfet, nMosfet, npn, opAmp, pMosfet, pnp } from "./symbols/transistors.ts";
import { chassisGround, earthGround, signalGround, supplyRail } from "./symbols/grounds.ts";
import { acSource, battery, currentSource, dcSource } from "./symbols/sources.ts";
import { pushButton, spdt, spst } from "./symbols/switches.ts";
import { icBox, junctionDot, junctionT, pinStub } from "./symbols/ic.ts";
import {
  amplifier,
  antenna,
  attenuator,
  bandPassFilter,
  bandStopFilter,
  highPassFilter,
  lowPassFilter,
  mixer,
  oscillator,
  pll,
  rfPort,
  variableAttenuator,
  vco,
  vga,
} from "./symbols/blocks.ts";

export const definitions: SymbolDefinition[] = [
  resistor,
  resistorAnsi,
  potentiometer,
  potentiometerAnsi,
  capacitor,
  polarizedCapacitor,
  variableCapacitor,
  inductor,
  coredInductor,
  ferriteBead,
  transformer,
  crystal,
  plainDiode,
  zener,
  schottky,
  led,
  varactor,
  photodiode,
  npn,
  pnp,
  nMosfet,
  pMosfet,
  nJfet,
  opAmp,
  comparator,
  dcSource,
  battery,
  acSource,
  currentSource,
  signalGround,
  chassisGround,
  earthGround,
  supplyRail,
  spst,
  spdt,
  pushButton,
  fuse,
  fuseAnsi,
  icBox,
  pinStub,
  junctionDot,
  junctionT,
  amplifier,
  vga,
  mixer,
  oscillator,
  vco,
  pll,
  lowPassFilter,
  highPassFilter,
  bandPassFilter,
  bandStopFilter,
  attenuator,
  variableAttenuator,
  antenna,
  rfPort,
];
